### ISSUE TITLE
fix unnessesary repeat profile update

### ISSUE THREAD

**Issue by ninyawee** [sakuguru/songmam#3]
when init `Page` with `persistent_menu`, `greeting` etc.

it usually hit the api limit. especially when developing. Thus, check if it the same before update will help.

```
Traceback (most recent call last):
  File "C:\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Python38\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python38\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\lifep\Devs\saku\saku\main.py", line 25, in <module>
    page = Page(
  File "C:\Users\lifep\Devs\saku\.venv\lib\site-packages\songmam\page.py", line 99, in __init__
    self._set_profile_property_sync(profile)
  File "C:\Users\lifep\Devs\saku\.venv\lib\site-packages\songmam\page.py", line 400, in _set_profile_property_sync
    raise Exception(r.text)
Exception: {"error":{"message":"(#613) Calls to this api have exceeded the rate limit.","type":"OAuthException","code":613,"fbtrace_id":"A62jI0OEScXiQBUU5BNxutz"}}
WARNING:  Detected file change in 'saku\main.py'. Reloading...
INFO:     Started server process [26692]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

**Comment by ninyawee** [comment]
@CircleOnCircles how to solve this
